config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  scope module: :public do
    get 'about' => 'homes#about'
    resources :organizers, only: [:show]
    resources :participations, only: [:create, :index, :show, :update]
    post 'participations/confirm' => 'participations#confirm', as: 'confirm'
    resource :user, only: [:show, :edit, :update]
    get 'user/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'user/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :events, only: [:index, :show] do
      resource :favorites, only: [:create, :destroy]
    end
    get 'favorites' => 'favorites#index'
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :organizers, except: [:destroy]
    resources :events, except: [:destroy] do
      resources :participations, only: [:index]
    end
  end

  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in', as: 'guest_sign_in'
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/organizer.rb
class Organizer < ApplicationRecord
  has_many :events, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, presence: true
  validates :homepage, presence: true

end

app/controllers/admin/organizers_controller.rb
class Admin::OrganizersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @organizers = Organizer.page(params[:page]).order(created_at: :desc)
  end

  def new
    @organizer = Organizer.new
  end

  def create
    @organizer = Organizer.new(organizer_params)
    if @organizer.save
      redirect_to admin_organizer_path(@organizer.id)
    else
      render :new
    end
  end

  def show
    @organizer = Organizer.find(params[:id])
  end
  
  def edit
    @organizer = Organizer.find(params[:id])
  end

  def update
    @organizer = Organizer.find(params[:id])
    if @organizer.update(organizer_params)
      redirect_to admin_organizer_path(@organizer.id)
    else
      render :edit
    end
  end

  private

  def organizer_params
    params.require(:organizer).permit(:name, :introduction, :postal_code, :address, :telephone_number, :email, :homepage)
  end
end

app/helpers/admin/organizers_helper.rb
module Admin::OrganizersHelper
end

app/views/admin/organizers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 offset-md-1">
      <h5 class="mt-4 mx-5 mb-2">主催者詳細編集</h5>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 offset-md-2">
      <% if @organizer.errors.any? %>
        <%= @organizer.errors.count %>件のエラーが発生しました
        <ul>
          <% @organizer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <%= form_with model: @organizer, url: admin_organizer_path do |f| %>
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <table class="table table-borderless">
          <tr>
            <th class="col-3"><%= f.label :name, "主催者名" %></th>
            <td><%= f.text_field :name, autocomplete: "name", placeholder: "主催者名", style: "width:100%" %></td>
          </tr>
          <tr>
            <th><%= f.label :introduction, "概要" %></th>
            <td><%= f.text_area :introduction, autocomplete: "introduction", placeholder: "ここに概要を記述します", style: "width:100%", rows: "5" %></td>
          </tr>
          <tr>
            <th><%= f.label :postal_code, "郵便番号" %></th>
            <td><%= f.text_field :postal_code, autocomplete: "postal_code", placeholder: "0000000", style: "width:40%" %></td>
          </tr>
          <tr>
            <th><%= f.label :address, "住所" %></th>
            <td><%= f.text_field :address, autocomplete: "address", placeholder: "新潟県新潟市中央区0-0", style: "width:100%" %></td>
          </tr>
          <tr>
            <th><%= f.label :telephone_number, "電話番号" %></th>
            <td><%= f.telephone_field :telephone_number, autocomplete: "telephone_number", placeholder: "00000000000", style: "width:100%" %></td>
          </tr>
          <tr>
            <th><%= f.label :email, "メールアドレス" %></th>
            <td><%= f.email_field :email, autocomplete: "email", placeholder: "sample@examle.com", style: "width:100%" %></td>
          </tr>
          <tr>
            <th><%= f.label :homepage, "ホームページ" %></th>
            <td><%= f.url_field :homepage, autocomplete: "homepage", placeholder: "http://aaaaa.ne.jp", style: "width:100%" %></td>
          </tr>
        </table>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <%= f.submit "変更を保存", class: "btn btn-success my-3 px-5" %>
    </div>
  <% end %>
</div>

app/views/admin/organizers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 offset-md-1 d-flex justify-content-between align-items-center mt-4 mb-2">
      <h5 class="mx-5 mb-0">主催者一覧</h5>
      <%= button_to new_admin_organizer_path, method: :get, class: "btn btn-circle" do %>
        <span style="color: #F99891"><i class="fas fa-plus"></i></span>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10 offset-md-1">
      <table class="table table-borderless">
        <tr>
          <th scope="col">No.</th>
          <th scope="col">主催者名</th>
          <th scope="col">電話番号</th>
          <th scope="col">住所</th>
        </tr>
        <% @organizers.each do |organizer| %>
          <tr>
            <td scope="row"><%= organizer.id %></td>
            <td>
              <%= link_to admin_organizer_path(organizer.id) do %>
                <%= organizer.name %>
              <% end %>
            </td>
            <td><%= organizer.telephone_number %></td>
            <td><%= organizer.address %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="d-flex justify-content-center mb-3">
    <%= paginate @organizers %>
  </div>
</div>

app/views/admin/organizers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 offset-md-1">
      <h5 class="mt-4 mx-5 mb-2">主催者新規登録</h5>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 offset-md-2">
      <% if @organizer.errors.any? %>
        <%= @organizer.errors.count %>件のエラーが発生しました
        <ul>
          <% @organizer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <%= form_with model: @organizer, url: admin_organizers_path do |f| %>
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <table class="table table-borderless">
          <tr>
            <th class="col-3"><%= f.label :name, "主催者名" %></th>
            <td><%= f.text_field :name, autocomplete: "name", placeholder: "主催者名", style: "width:100%" %></td>
          </tr>
          <tr>
            <th><%= f.label :introduction, "概要" %></th>
            <td><%= f.text_area :introduction, autocomplete: "introduction", placeholder: "ここに概要を記述します", style: "width:100%", rows: "5" %></td>
          </tr>
          <tr>
            <th><%= f.label :postal_code, "郵便番号" %></th>
            <td><%= f.text_field :postal_code, autocomplete: "postal_code", placeholder: "0000000", style: "width:40%" %></td>
          </tr>
          <tr>
            <th><%= f.label :address, "住所" %></th>
            <td><%= f.text_field :address, autocomplete: "address", placeholder: "新潟県新潟市中央区0-0", style: "width:100%" %></td>
          </tr>
          <tr>
            <th><%= f.label :telephone_number, "電話番号" %></th>
            <td><%= f.telephone_field :telephone_number, autocomplete: "telephone_number", placeholder: "00000000000", style: "width:100%" %></td>
          </tr>
          <tr>
            <th><%= f.label :email, "メールアドレス" %></th>
            <td><%= f.email_field :email, autocomplete: "email", placeholder: "sample@examle.com", style: "width:100%" %></td>
          </tr>
          <tr>
            <th><%= f.label :homepage, "ホームページ" %></th>
            <td><%= f.url_field :homepage, autocomplete: "homepage", placeholder: "http://aaaaa.ne.jp", style: "width:100%" %></td>
          </tr>
        </table>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <%= f.submit "新規登録", class: "btn btn-success my-3 px-5" %>
    </div>
  <% end %>
</div>

app/views/admin/organizers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 offset-md-1">
      <h5 class="mt-4 mx-5 mb-2"><%= @organizer.name %></h5>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10 offset-md-1">
      <table class="table table-borderless">
        <tr>
          <th class="col-3">主催者No.</th>
          <td><%= @organizer.id %></td>
        </tr>
        <tr>
          <th class="d-flex align-items-stretch">詳細</th>
          <td><%=safe_join(@organizer.introduction.split("\n"),tag(:br))%></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @organizer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @organizer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @organizer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @organizer.email %></td>
        </tr>
        <tr>
          <th>ホームページURL</th>
          <td><%= link_to @organizer.homepage, @organizer.homepage %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "編集する", edit_admin_organizer_path(@organizer.id), class: "btn btn-success my-3 px-5" %>
  </div>
</div>