config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  scope module: :public do
    get 'about' => 'homes#about'
    resources :organizers, only: [:show]
    resources :participations, only: [:create, :index, :show, :update]
    post 'participations/confirm' => 'participations#confirm', as: 'confirm'
    resource :user, only: [:show, :edit, :update]
    get 'user/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'user/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :events, only: [:index, :show] do
      resource :favorites, only: [:create, :destroy]
    end
    get 'favorites' => 'favorites#index'
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :organizers, except: [:destroy]
    resources :events, except: [:destroy] do
      resources :participations, only: [:index]
    end
  end

  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in', as: 'guest_sign_in'
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :participations, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :organizer
  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :date, presence: true
  validates :place, presence: true
  validates :schedule, presence: true
  validates :number_of_people, presence: true
  validates :organizer_id, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @events = Event.page(params[:page]).order(created_at: :desc)
  end

  def new
    @event = Event.new
    @organizers = Organizer.all
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to admin_event_path(@event.id)
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end
  
  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to admin_event_path(@event.id)
    else
      render :edit
    end
  end
  
  private

  def event_params
    params.require(:event).permit(:organizer_id, :name, :introduction, :date, :place, :schedule, :number_of_people, :is_recruiting, :image)
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/views/admin/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 offset-md-1">
      <h5 class="mt-4 mx-5 mb-2">イベント内容編集</h5>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 offset-md-2">
      <% if @event.errors.any? %>
        <%= @event.errors.count %>件のエラーが発生しました
        <ul>
          <% @event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <%= form_with model: @event, url: admin_event_path do |f| %>
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <table class="table table-borderless">
          <tr>
            <th class="col-3"><%= f.label :organizer_id, "主催者" %></th>
            <td><%= f.collection_select :organizer_id, Organizer.all, :id, :name %></td>
          </tr>
          <tr>
            <th><%= f.label :name, "イベント名" %></th>
            <td>
              <%= f.text_field :name, autocomplete: "name", placeholder: "イベント名", style: "width:100%" %>
              <% if @event.errors.any? %>
                <% if @event.errors.has_key?(:name) %>
                  <p class="text-danger"><%= @event.errors[:name].first %></p>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :introduction, "概要" %></th>
            <td>
              <%= f.text_area :introduction, autocomplete: "introduction", placeholder: "ここにイベント概要を記述します", style: "width:100%", rows: "7" %>
              <% if @event.errors.any? %>
                <% if @event.errors.has_key?(:introduction) %>
                  <p class="text-danger"><%= @event.errors[:introduction].first %></p>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :date, "日付" %></th>
            <td>
              <%= f.date_field :date %>
              <% if @event.errors.any? %>
                <% if @event.errors.has_key?(:date) %>
                  <p class="text-danger"><%= @event.errors[:date].first %></p>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :place, "場所" %></th>
            <td>
              <%= f.text_field :place, autocomplete: "place", placeholder: "開催地", style: "width:100%" %>
              <% if @event.errors.any? %>
                <% if @event.errors.has_key?(:place) %>
                  <p class="text-danger"><%= @event.errors[:place].first %></p>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :schedule, "スケジュール" %></th>
            <td>
              <%= f.text_area :schedule, autocomplete: "schedule", placeholder: "30日11:00　集合", style: "width:100%", rows: "5" %>
              <% if @event.errors.any? %>
                <% if @event.errors.has_key?(:schedule) %>
                  <p class="text-danger"><%= @event.errors[:schedule].first %></p>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :number_of_people, "募集予定人数" %></th>
            <td>
              <div class="d-flex">
                <%= f.number_field :number_of_people, placeholder: "10", min: "1" %>人
              </div>
              <% if @event.errors.any? %>
                <% if @event.errors.has_key?(:number_of_people) %>
                  <p class="text-danger"><%= @event.errors[:number_of_people].first %></p>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :is_recruiting, "募集状況" %></th>
            <td>
              <% if @event.is_recruiting == true %>
                <%= f.radio_button :is_recruiting, true, checked: true %>
                <%= f.label :is_recruiting_true, "募集中" %>
                <%= f.radio_button :is_recruiting, false %>
                <%= f.label :is_recruiting_false, "締切" %>
              <% else %>
                <%= f.radio_button :is_recruiting, true %>
                <%= f.label :is_recruiting_true, "募集中" %>
                <%= f.radio_button :is_recruiting, false, checked: true %>
                <%= f.label :is_recruiting_false, "締切" %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :image, "画像" %></th>
            <td><%= f.file_field :image, accept: "image/*", style: "width:100%" %><br>※任意</td>
          </tr>
        </table>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <%= f.submit "変更を保存", class: "btn btn-success my-3 px-5" %>
    </div>
  <% end %>
</div>

app/views/admin/events/index.html.erb
<div class="container">
  <div class="d-flex justify-content-center mt-3">
    <div class="notice"><%= notice %></div>
  </div>

  <div class="row">
    <div class="col-md-9 offset-md-1 d-flex justify-content-between align-items-center mt-2 mb-2">
      <h5 class="mx-5 mb-0">イベント一覧</h5>
      <%= button_to new_admin_event_path, method: :get, class: "btn btn-circle" do %>
        <span style="color: #F99891"><i class="fas fa-plus"></i></span>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10 offset-md-1">
      <table class="table table-borderless">
        <tr>
          <th>No.</th>
          <th>イベント名</th>
          <th>開催日</th>
          <th>応募人数</th>
          <th>募集状況</th>
          <th>いいね</th>
        </tr>
        <% @events.each do |event| %>
          <tr>
            <td scope="row"><%= event.id %></td>
            <td>
              <%= link_to admin_event_path(event.id) do %>
                <%= event.name %>
              <% end %>
            </td>
            <td><%= event.date.strftime('%Y/%m/%d') %></td>
            <td>
              <%= link_to admin_event_participations_path(event.id) do %>
                <%= event.participations.select { |participation| participation.is_applying == true }.count %>名
              <% end %>
              </td>
            <td>
              <% if event.is_recruiting == true %>
                <p class="text-success m-0"><strong>募集中</strong></p>
              <% else %>
                <p class="text-secondary m-0">締切</p>
              <% end %>
            </td>
            <td><i class="fas fa-heart color_pink"></i> <%= event.favorites.count %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="d-flex justify-content-center mb-3">
    <%= paginate @events %>
  </div>
</div>

app/views/admin/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 offset-md-1">
      <h5 class="mt-4 mx-5 mb-2">イベント新規登録</h5>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 offset-md-2">
      <% if @event.errors.any? %>
        <%= @event.errors.count %>件のエラーが発生しました
        <ul>
          <% @event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <%= form_with model: @event, url: admin_events_path do |f| %>
    <div class="row">
      <div class="col-md-10 offset-md-1">
        <table class="table table-borderless">
          <tr>
            <th class="col-3"><%= f.label :organizer_id, "主催者" %></th>
            <td><%= f.collection_select :organizer_id, Organizer.all, :id, :name %></td>
          </tr>
          <tr>
            <th><%= f.label :name, "イベント名" %></th>
            <td>
              <%= f.text_field :name, autocomplete: "name", placeholder: "イベント名", style: "width:100%" %>
              <% if @event.errors.any? %>
                <% if @event.errors.has_key?(:name) %>
                  <p class="text-danger"><%= @event.errors[:name].first %></p>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :introduction, "概要" %></th>
            <td>
              <%= f.text_area :introduction, autocomplete: "introduction", placeholder: "ここにイベント概要を記述します", style: "width:100%", rows: "7" %>
              <% if @event.errors.any? %>
                <% if @event.errors.has_key?(:introduction) %>
                  <p class="text-danger"><%= @event.errors[:introduction].first %></p>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :date, "日付" %></th>
            <td>
              <%= f.date_field :date %>
              <% if @event.errors.any? %>
                <% if @event.errors.has_key?(:date) %>
                  <p class="text-danger"><%= @event.errors[:date].first %></p>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :place, "場所" %></th>
            <td>
              <%= f.text_field :place, autocomplete: "place", placeholder: "開催地", style: "width:100%" %>
              <% if @event.errors.any? %>
                <% if @event.errors.has_key?(:place) %>
                  <p class="text-danger"><%= @event.errors[:place].first %></p>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :schedule, "スケジュール" %></th>
            <td>
              <%= f.text_area :schedule, autocomplete: "schedule", placeholder: "30日11:00　集合", style: "width:100%", rows: "5" %>
              <% if @event.errors.any? %>
                <% if @event.errors.has_key?(:schedule) %>
                  <p class="text-danger"><%= @event.errors[:schedule].first %></p>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :number_of_people, "募集予定人数" %></th>
            <td>
              <div class="d-flex">
                <%= f.number_field :number_of_people, placeholder: "10", min: "1" %>人
              </div>
              <% if @event.errors.any? %>
                <% if @event.errors.has_key?(:number_of_people) %>
                  <p class="text-danger"><%= @event.errors[:number_of_people].first %></p>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><%= f.label :image, "画像" %></th>
            <td><%= f.file_field :image, accept: "image/*", style: "width:100%" %><br>※任意</td>
          </tr>
        </table>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <%= f.submit "新規登録", class: "btn btn-success my-3 px-5" %>
    </div>
  <% end %>
</div>

app/views/admin/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 offset-md-1">
      <h5 class="mt-4 mx-5 mb-3">イベント詳細</h5>
    </div>
  </div>

  <div class="row">
    <div class="col-md-10 offset-md-1">
      <table class="table table-borderless">
        <%= render 'public/shared/event_detail', event: @event %>
        <tr>
          <th>応募人数</th>
          <td>
            <%= link_to admin_event_participations_path(@event.id) do %>
              <%= @event.participations.select { |participation| participation.is_applying == true }.count %>名
            <% end %>
          </td>
        </tr>
        <tr>
          <th>募集状況</th>
          <td>
            <% if @event.is_recruiting == true %>
              <p class="text-success m-0"><strong>募集中</strong></p>
            <% else %>
              <p class="text-secondary m-0">締切</p>
            <% end %>
          </td>
        </tr>
      </table>
      <div class="pt-3 pr-5">
        <%= image_tag @event.get_image.variant(resize: "250x200^", gravity: "center", crop: "250x200+0+0").processed %>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "編集する", edit_admin_event_path(@event.id), class: "btn btn-success my-3 px-5" %>
  </div>
</div>