config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  scope module: :public do
    get 'about' => 'homes#about'
    resources :organizers, only: [:show]
    resources :participations, only: [:create, :index, :show, :update]
    post 'participations/confirm' => 'participations#confirm', as: 'confirm'
    resource :user, only: [:show, :edit, :update]
    get 'user/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'user/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :events, only: [:index, :show] do
      resource :favorites, only: [:create, :destroy]
    end
    get 'favorites' => 'favorites#index'
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :organizers, except: [:destroy]
    resources :events, except: [:destroy] do
      resources :participations, only: [:index]
    end
  end

  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in', as: 'guest_sign_in'
  end

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Borakatsu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/31bc79c05c.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="sticky-top">
      <div class="container">
        <nav class="navbar navbar-expand-md navbar-dark">
          <a class="navbar-brand" href="/"><%= image_tag "logo.jpg", width: '90' %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto"></ul>
            <ul class="navbar-nav">

              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "マイページ", user_path, class: 'nav-link px-2' %>
                </li>
                <li class="nav-item">
                  <%= link_to "イベント一覧", events_path, class: 'nav-link px-2 ml-md-5' %>
                </li>
                <li class="nav-item">
                  <%= link_to "いいね一覧", favorites_path, class: 'nav-link px-2 ml-md-5' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link px-2 ml-md-5' %>
                </li>

              <% elsif admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "イベント一覧",  admin_events_path, class: 'nav-link px-2' %>
                </li>
                <li class="nav-item">
                  <%= link_to "会員一覧", admin_users_path, class: 'nav-link px-2 ml-md-5' %>
                </li>
                <li class="nav-item">
                  <%= link_to "主催者一覧", admin_organizers_path, class: 'nav-link px-2 ml-md-5' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link px-2 ml-md-5' %>
                </li>

              <% else %>
                <li class="nav-item">
                  <%= link_to "About", about_path, class: 'nav-link px-2' %>
                </li>
                <li class="nav-item">
                  <%= link_to "イベント一覧", events_path, class: 'nav-link px-2 ml-md-5' %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link px-2 ml-md-5' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link px-2 ml-md-5' %>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <p>© All Rights Reserved.</p>
    </footer>
  </body>
</html>